### ISSUE TITLE
Disable messages on Debian Stable

### ISSUE THREAD

**Issue by treaki** [Natenom/wrongversion#1]
Hi,

i am annoyed by the messages shown me everytime i connect to the mumble server "Natemologie-Zentrum (Opus)" using my debian with the Debian i get sued by it because my mumble version is to old. I am using debian stables mumble version which is the latest available!

So please disable that message for the latest debian version (currently 1.2.8-2)

thanks a lot

ps: i had made a pull request but i'm not a python guy...

**Comment by Natenom** [comment]
I will expand this to all non Windows systems ...

**Comment by Natenom** [comment]
Better solution: Only include Windows and Mac OS system because these both systems are only covered by binary packages from the Mumble project.
